---
abstract: 'Accept-Language header parser and find available language'
author:
  - 'Kazuhiro Osawa <yappo {at} shibuya {dot} pl>'
build_requires:
  Test::More: 0.88
configure_requires:
  Module::Build::Tiny: 0.027
dynamic_config: 0
generated_by: 'Dist::Milla version v1.0.4, Dist::Zilla version 4.300039, CPAN::Meta::Converter version 2.132620'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: HTTP-AcceptLanguage
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
requires:
  perl: 5.008005
resources:
  bugtracker: https://github.com/yappo/p5-HTTP-AcceptLanguage/issues
  homepage: https://github.com/yappo/p5-HTTP-AcceptLanguage
  repository: https://github.com/yappo/p5-HTTP-AcceptLanguage.git
version: 0.02
x_contributors:
  - 'Kazuhiro Osawa <yappo@shibuya.pl>'
  - 'tokuhirom <tokuhirom@gmail.com>'
